"""
SECURA-9 Provisioning HTTP Server
Serves setup UI on port 8080, receives Firebase credentials + device config.
"""
import json
import logging
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../..'))
import config

log = logging.getLogger('provisioning')

SETUP_HTML = """<!DOCTYPE html>
<html><head>
<title>SECURA-9 Setup</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
body{font-family:monospace;background:#0a0210;color:#c8e6ff;margin:0;padding:20px}
h1{color:#00ffff;text-align:center;font-size:24px}
.card{background:#140523;border:1px solid #1e0a32;border-radius:8px;padding:20px;max-width:500px;margin:20px auto}
label{display:block;margin:12px 0 4px;color:#5a5078;font-size:12px}
textarea,input,select{width:100%;background:#0a0210;border:1px solid #1e0a32;color:#00ffff;padding:8px;border-radius:4px;font-family:monospace;box-sizing:border-box}
button{background:#00ffff;color:#0a0210;border:none;padding:12px;width:100%;border-radius:4px;font-weight:bold;cursor:pointer;font-size:16px;margin-top:16px}
button:hover{background:#39ff14}
.note{color:#5a5078;font-size:11px;text-align:center;margin-top:12px}
.ok{color:#39ff14;text-align:center;font-size:18px;padding:20px}
.err{color:#ff007f;text-align:center;padding:10px}
</style></head><body>
<h1>SECURA-9 SETUP</h1>
<div class="card" id="form">
<label>DEVICE NAME</label>
<input type="text" id="device_name" placeholder="secura9_pi_01" value="secura9_pi_01">
<label>FIREBASE SERVICE ACCOUNT (JSON)</label>
<textarea id="firebase_json" rows="10" placeholder='Paste your Firebase service account JSON here'></textarea>
<label>CAMERA SOURCE</label>
<select id="camera_source"><option value="0">Built-in camera (0)</option><option value="1">USB camera (1)</option><option value="http">IP camera URL</option></select>
<label>DISPLAY MODE</label>
<select id="display_mode"><option value="720x1280">720x1280 Portrait</option><option value="800x480">800x480 Landscape</option><option value="1920x1080">1920x1080 HD</option><option value="headless">Headless (no display)</option></select>
<button onclick="submitSetup()">CONFIGURE DEVICE</button>
<div class="note">Device will reboot after successful configuration</div>
</div>
<div class="ok" id="ok" style="display:none">&#10003; DEVICE CONFIGURED<br><small>Rebooting...</small></div>
<div class="err" id="err" style="display:none"></div>
<script>
async function submitSetup(){const b=document.getElementById;const r=await fetch('/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device_name:b('device_name').value,firebase_json:b('firebase_json').value,camera_source:b('camera_source').value,display_mode:b('display_mode').value})});const d=await r.json();if(r.ok){b('form').style.display='none';b('ok').style.display='block'}else{b('err').textContent=d.error;b('err').style.display='block'}}
</script></body></html>"""


class SetupHandler:
    def __init__(self):
        self._server = None

    def handle_setup(self, body):
        device_name = body.get('device_name', 'secura9_pi_01')
        firebase_json = body.get('firebase_json', '')
        camera_source = body.get('camera_source', '0')
        display_mode = body.get('display_mode', '720x1280')

        # Validate Firebase JSON
        if not firebase_json.strip():
            return {'error': 'Firebase service account JSON is required'}
        try:
            fb_creds = json.loads(firebase_json)
        except json.JSONDecodeError:
            return {'error': 'Invalid JSON in Firebase credentials'}

        if 'project_id' not in fb_creds:
            return {'error': 'Not a valid Firebase service account key (missing project_id)'}

        # Parse display mode
        if display_mode == 'headless':
            disp_w, disp_h, headless = 720, 1280, True
        else:
            parts = display_mode.split('x')
            disp_w, disp_h = int(parts[0]), int(parts[1])
            headless = False

        # Parse camera source
        cam_src = int(camera_source) if camera_source.isdigit() else camera_source

        # Build device config
        device_config = {
            '__comment': 'SECURA-9 device config — generated by first-boot setup',
            'device_id': device_name,
            'camera': {
                'source': cam_src,
                'width': 640,
                'height': 480,
                'fps': 30,
                'flip_horizontal': True,
            },
            'display': {
                'width': disp_w,
                'height': disp_h,
                'fullscreen': True,
                'headless': headless,
            },
            'door': {
                'relay_pin': 17,
                'open_seconds': 5,
            },
            'stt': {
                'lang': 'bn-IN',
                'timeout': 12,
            },
        }

        # Write files
        os.makedirs('/etc/secura9', exist_ok=True)
        try:
            with open('/etc/secura9/config.json', 'w') as f:
                json.dump(device_config, f, indent=2)
            with open('/etc/secura9/firebase.json', 'w') as f:
                json.dump(fb_creds, f, indent=2)
            with open('/etc/secura9/device_id', 'w') as f:
                f.write(device_name.strip())
            log.info('Provisioning files written to /etc/secura9/')
        except Exception as e:
            log.error(f'Failed to write config: {e}')
            return {'error': f'Failed to write config: {e}'}

        return {'ok': True}

    def start(self):
        from http.server import HTTPServer, BaseHTTPRequestHandler

        handler = self

        class _ReqHandler(BaseHTTPRequestHandler):
            def _send(self, code, data):
                self.send_response(code)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps(data).encode())

            def do_GET(self):
                if self.path in ('/', '/setup'):
                    self.send_response(200)
                    self.send_header('Content-Type', 'text/html')
                    self.end_headers()
                    self.wfile.write(SETUP_HTML.encode())
                else:
                    self.send_response(404)
                    self.end_headers()

            def do_POST(self):
                if self.path != '/setup':
                    self._send(404, {'error': 'not found'})
                    return
                try:
                    length = int(self.headers.get('Content-Length', 0))
                    raw = self.rfile.read(length)
                    body = json.loads(raw)
                    result = handler.handle_setup(body)
                    if result.get('ok'):
                        self._send(200, result)
                    else:
                        self._send(400, result)
                except Exception as e:
                    self._send(500, {'error': str(e)})

            def log_message(self, fmt, *args):
                log.debug(f'HTTP: {fmt % args}')

        server = HTTPServer(('0.0.0.0', 8080), _ReqHandler)
        log.info('Setup server listening on http://0.0.0.0:8080')
        server.serve_forever()
